export const AUTH_SIGN_IN = 'AUTH_SIGN_IN'
export const AUTH_SIGN_IN_PENDING = 'AUTH_SIGN_IN_PENDING'
export const AUTH_SIGN_IN_FULFILLED = 'AUTH_SIGN_IN_FULFILLED'
export const AUTH_SIGN_IN_REJECTED = 'AUTH_SIGN_IN_REJECTED'
