const DEFAULT_BCRYPT_NUM_ROUNDS = 10
const DEFAULT_JWT_SECRET_KEY = 'supersafesecretkey'
const DEFAULT_JWT_EXPIRATION_TIME = '1m'

const config = {
  BCRYPT_NUM_ROUNDS: process.env.ANUBIS_BCRYPT_NUM_ROUNDS || DEFAULT_BCRYPT_NUM_ROUNDS,
  JWT_SECRET_KEY: process.env.ANUBIS_JWT_SECRET_KEY || DEFAULT_JWT_SECRET_KEY,
  JWT_EXPIRATION_TIME: process.env.ANUBIS_JWT_EXPIRATION_TIME || DEFAULT_JWT_EXPIRATION_TIME
}

export default config
