export const AUTH_SIGN_IN = 'AUTH_SIGN_IN'
export const AUTH_SIGN_IN_PENDING = 'AUTH_SIGN_IN_PENDING'
export const AUTH_SIGN_IN_FULFILLED = 'AUTH_SIGN_IN_FULFILLED'
export const AUTH_SIGN_IN_REJECTED = 'AUTH_SIGN_IN_REJECTED'

export const AUTH_SIGN_UP = 'AUTH_SIGN_UP'
export const AUTH_SIGN_UP_PENDING = 'AUTH_SIGN_UP_PENDING'
export const AUTH_SIGN_UP_FULFILLED = 'AUTH_SIGN_UP_FULFILLED'
export const AUTH_SIGN_UP_REJECTED = 'AUTH_SIGN_UP_REJECTED'

export const AUTH_RESET_SIGN_IN_COMPLETED_FLAG = 'AUTH_RESET_SIGN_IN_COMPLETED_FLAG'
export const AUTH_RESET_SIGN_UP_COMPLETED_FLAG = 'AUTH_RESET_SIGN_UP_COMPLETED_FLAG'

export const AUTH_SIGN_OUT = 'AUTH_SIGN_OUT'
export const AUTH_INJECT_ACCESS_TOKEN = 'AUTH_INJECT_ACCESS_TOKEN'
