export const DEVICE_FETCH_ALL = 'DEVICE_FETCH_ALL'
export const DEVICE_FETCH_ALL_PENDING = 'DEVICE_FETCH_ALL_PENDING'
export const DEVICE_FETCH_ALL_FULFILLED = 'DEVICE_FETCH_ALL_FULFILLED'
export const DEVICE_FETCH_ALL_REJECTED = 'DEVICE_FETCH_ALL_REJECTED'

export const DEVICE_CREATE = 'DEVICE_CREATE'
export const DEVICE_CREATE_PENDING = 'DEVICE_CREATE_PENDING'
export const DEVICE_CREATE_FULFILLED = 'DEVICE_CREATE_FULFILLED'
export const DEVICE_CREATE_REJECTED = 'DEVICE_CREATE_REJECTED'

export const DEVICE_UPDATE = 'DEVICE_UPDATE'
export const DEVICE_UPDATE_PENDING = 'DEVICE_UPDATE_PENDING'
export const DEVICE_UPDATE_FULFILLED = 'DEVICE_UPDATE_FULFILLED'
export const DEVICE_UPDATE_REJECTED = 'DEVICE_UPDATE_REJECTED'

export const DEVICE_DELETE = 'DEVICE_DELETE'
export const DEVICE_DELETE_PENDING = 'DEVICE_DELETE_PENDING'
export const DEVICE_DELETE_FULFILLED = 'DEVICE_DELETE_FULFILLED'
export const DEVICE_DELETE_REJECTED = 'DEVICE_DELETE_REJECTED'

export const DEVICE_FETCH_DETAILS = 'DEVICE_FETCH_DETAILS'
export const DEVICE_FETCH_DETAILS_PENDING = 'DEVICE_FETCH_DETAILS_PENDING'
export const DEVICE_FETCH_DETAILS_FULFILLED = 'DEVICE_FETCH_DETAILS_FULFILLED'
export const DEVICE_FETCH_DETAILS_REJECTED = 'DEVICE_FETCH_DETAILS_REJECTED'
