export const USER_FETCH_DETAILS = 'USER_FETCH_DETAILS'
export const USER_FETCH_DETAILS_PENDING = 'USER_FETCH_DETAILS_PENDING'
export const USER_FETCH_DETAILS_FULFILLED = 'USER_FETCH_DETAILS_FULFILLED'
export const USER_FETCH_DETAILS_REJECTED = 'USER_FETCH_DETAILS_REJECTED'

export const USER_CLEAR_DETAILS = 'USER_CLEAR_DETAILS'
